---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mongo-storage
  namespace: act-namespace
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  fstype: ext4
  replication-type: none

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: act-namespace
spec:
  resources:
    requests:
      storage: 3Gi
  storageClassName: mongo-storage
  accessModes:
    - ReadWriteOnce