kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: mongo-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: ext4 

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  resources:
    requests:
      storage: 3Gi
  storageClassName: mongo-storage
  accessModes:
    - ReadWriteOnce